project:
  type: book
  output-dir: docs

lang: "de"

profile:
  default: book
  group:
    - [book, slides]

language:
  toc-title: "Inhalt"
  chapter: "Kapitel"
  appendix: "Anhang"
  references: "Literatur"
  next: "Weiter"
  previous: "Zurück"

book:
  title: "Gravimetrie"
  subtitle: "Modul Gravimetrie und Magnetik"
  author: "Ralph-Uwe Börner"
  date: today
  chapters:
    - index.qmd
    - grundlagen.qmd
    - slidedecks.qmd

format: 
  html:
    theme: cosmo
    number-sections: true
    lib-dir: site_libs
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: {
              load: ['[tex]/physics']
            },
            tex: {
              packages: {'[+]': ['physics']}
            }
          };
          </script>
 
editor: source